### ISSUE TITLE
Add ability to download EXIF data as JSON

### ISSUE THREAD

**Issue by BlockArchitech** [BlockArchitech/gexif#1]
Soon, I want to be able to add the ability to download the data as a JSON file, particularly in multi-image mode.

This will have to be worked on, but I'll have to find a way to extract the exif data and create a file.

**Comment by BlockArchitech** [comment]
Please make sure if you are submitting a pull request you put "Closes #1" in your description.

**Comment by raccodee** [comment]
I was browsing through help wanted and I saw this issue, do you still need help? You don’t actually need to convert it to a file.

Let me know!

**Comment by BlockArchitech** [comment]
If you could help, that would be great! Let me know what you think of.

**Comment by raccodee** [comment]
@BlockArchitech Sure thing! Count me in, will make a PR soon.

**Comment by BlockArchitech** [comment]
#2 Added this! Thanks again!
