### ISSUE TITLE
Fails to extract EXIF data from TIFF images

### ISSUE THREAD

**Issue by ghost** [blockarchitech/gexif#3]
Seems like the only widely known browser that supports TIFF natively is Safari: http://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

In the rest of the browsers the image won't load and the data won't be extracted. In Safari the image loads but EXIF.js is not able to extract any data from it.

**Comment by BlockArchitech** [comment]
Hmm. This is interesting. I can go ahead and add a flash message at top of page until I find a way to get around this.

**Comment by BlockArchitech** [comment]
Speaking of safari - looks like some of the buttons don't display correctly/at all.

Console:
```
[Error] TypeError: null is not an object (evaluating 'downloadBtn.classList')
	(anonymous function) (main.js:53)
	t (exif-js:7:7892)
	r (exif-js:7:7942)
	(anonymous function) (exif-js:7:14003)
	(anonymous function) (main.js:28)
	
```

**Comment by BlockArchitech** [comment]
Branch for development: `TIFF-BUTTON-FIX`

**Comment by raccodee** [comment]
Yeah we just stepped into the wonderful world of the browsers war :D. Bear in mind that Safari keeps the web development hostage in 2016, every API has some trouble working there. But there are polyfills.
